### ISSUE TITLE
which function return element or value selected?

### ISSUE THREAD

**Issue by captainhamid** [daneWilliams/jquery.dropdown#18]
how to get id element  li ?

**Comment by daneWilliams** [comment]
The `dropdown-before-select` and `dropdown-after-select` callback events will return the selected item. The value and element can be retrieved from that;

````
$('.dropdown').on( 'dropdown-after-select', function( e, item, previous, dropdown ) {

    console.log( item );

    // Get the value
    var value = item.value;

    // Get the element
    var elem = item.elem;

});
````

**Comment by ulybu** [comment]
Hey Dane,

Would be nice to have those events  documented or at least listed (as some are quite self explanatory) on the doc: http://dane.one/projects/jquery-dropdown/docs/

Same for the methods, listed in #20 

I'm used to look in the code if there is no doc, but when I found one I tend to assume everything is listed (even more when it is pretty). Events are a nice feature it would be sad if people don't use your dropdown because they think the dropdown lacks a proper API.

Secondly, **for those reading this ticket from a search, the name of the event has changed**, it is now `dropdown.select`. Found it in the source:

```js
_afterSelect: function( item, prev ) {
  var self = this;

  // Update <select /> value
  if ( 'SELECT' == self.$elem.prop( 'tagName' ) )
  self.$elem.val( self.inst.value );

  // Event
  self.$elem.trigger( self.name + '.select', [ item, prev, this ] );
},
```

Cheers
